### ISSUE TITLE
"none of them works fully offline (mopidy)"

### ISSUE THREAD

**Issue by kingosticks** [TestDotCom/pirateplayer#1]
I stumbled upon your project but I am confused by the sentence:

> none of them works fully offline (mopidy)

Could you expand on this? Mopidy can playback local files (on the sd card or from a usb device) and does not require network access.

**Comment by kingosticks** [comment]
If I had thought about it for 1 more minute I would have understood. You were talking about having an interface displayed on the screen and using the buttons to select music; therefore avoiding the need for another controlling device (e.g. smart phone) on the same local network. I am with you now. Apologies for the noise.

**Comment by kingosticks** [comment]
Although I wonder how much work it would be to adapt something like this to run as a Mopidy frontend. I may just explore that. Thanks for your project!

**Comment by testdotcom** [comment]
> Although I wonder how much work it would be to adapt something like this to run as a Mopidy frontend. I may just explore that. Thanks for your project!

From what I saw Mopidy docs are well written, if you want to fork this and make a frontend go for it ;)
