### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by rnsi** [TestDotCom/pirateplayer#2]
Trying to install on a new Raspberry Pi OS Lite, latest from Dec 2020. After resolving dependencies, running priateplayer gives the following error:

[~]#> pirateplayer
Traceback (most recent call last):
  File "/usr/local/bin/pirateplayer", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pirateplayer/__main__.py", line 20, in main
    pins = confparse.get_pins()
  File "/usr/local/lib/python3.7/dist-packages/pirateplayer/utils/confparse.py", line 24, in get_pins
    return list(_CONF['BUTTON'].getint(btn) for btn in _CONF['BUTTON'])
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'BUTTON'

Running on a RPi Zero W, installed pirateplayer from pip3.

Any suggestions?
Thanks,
rnsi

**Comment by testdotcom** [comment]
Have you run install.sh? It makes a systemd service and writes a config file (it seems you don't have it)

**Comment by rnsi** [comment]
I can't find install.sh. Where should it be?

Thanks

**Comment by rnsi** [comment]
I copied it from here. Still not playing sound though.

**Comment by testdotcom** [comment]
Sorry but you have to be more specific, else I can't help you

- are you using the default jack on the rpi or some other module?
- can you provide the python execution log?

**Comment by rnsi** [comment]
I missed a step, installing hifiberry dac. Started over and it's working now.
