### ISSUE TITLE
Continuous playing

### ISSUE THREAD

**Issue by UxFFFD** [TestDotCom/pirateplayer#4]
I've managed (with help from the issue from @andygmassey) to install PiratePlayer and it works like a breeze! The only issue I have is, that it doesn't play the tracks continuously. If a track ends, it doesn't play the next one. How can I achieve that? I am a frontend-developer hobbyist and have not much experience with python. I am learning right now with my RPIs... Any advice would be much appreciated!

**Comment by paultheastronomer** [comment]
This feature would be nice indeed. I would be happy to try and implement it. Are you accepting pull requests @TestDotCom ? Could you let me know where to start?

**Comment by testdotcom** [comment]
Hey guys thanks for the interest! Unfortunately I don't have enough free time to follow this project. However, you are free to fork it and experiment for yourself
